[package]
name = "gpui_study"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
cpal = "0.16.0"
gpui = "0.2.2"
lofty = "0.22.4"
ringbuf = "0.4.8"
rodio = "0.21.1"
rust-embed = "8.9.0"
symphonia = "0.5.5"
